"""无 ROS、MuJoCo 依赖的 DMgripper 共享控制核。"""

from .control import (
    AdrcConfig,
    ContactStiffnessConfig,
    ContactStiffnessEstimator,
    CrankSliderKinematics,
    DAMIAO_DAMPING_RANGE,
    DAMIAO_GAIN_BITS,
    DAMIAO_POSITION_BITS,
    DAMIAO_STIFFNESS_RANGE,
    DAMIAO_TORQUE_BITS,
    DAMIAO_VELOCITY_BITS,
    ForceControlObservation,
    ForceControlReference,
    ForceSemantics,
    MITControlCommand,
    MITControlConfig,
    MITTorqueInner,
    MITTorqueModel,
    NormalForceConfig,
    NormalForceControlCommand,
    NormalForceController,
    SecondOrderAdmittance,
    SecondOrderTorqueLADRC,
    TorqueAdrcConfig,
    TorqueAdrcStep,
    limit_mit_position_for_torque,
)
from .grasp import (
    ContactTransition,
    MITCommand,
    MITCommandConfig,
    MinimumJerkTrajectory,
    build_mit_command,
    quintic_blend,
    step_admittance,
)
from .tactile import ContactDetector, within_zero_window

__version__ = "0.1.0"
__all__ = [
    "AdrcConfig",
    "ContactStiffnessConfig",
    "ContactStiffnessEstimator",
    "CrankSliderKinematics",
    "DAMIAO_DAMPING_RANGE",
    "DAMIAO_GAIN_BITS",
    "DAMIAO_POSITION_BITS",
    "DAMIAO_STIFFNESS_RANGE",
    "DAMIAO_TORQUE_BITS",
    "DAMIAO_VELOCITY_BITS",
    "ForceControlObservation",
    "ForceControlReference",
    "ForceSemantics",
    "MinimumJerkTrajectory",
    "MITCommand",
    "MITCommandConfig",
    "MITControlCommand",
    "MITControlConfig",
    "MITTorqueInner",
    "MITTorqueModel",
    "NormalForceConfig",
    "NormalForceControlCommand",
    "NormalForceController",
    "quintic_blend",
    "SecondOrderAdmittance",
    "SecondOrderTorqueLADRC",
    "TorqueAdrcConfig",
    "TorqueAdrcStep",
    "limit_mit_position_for_torque",
    "ContactTransition",
    "ContactDetector",
    "within_zero_window",
    "build_mit_command",
    "step_admittance",
]
