# @package model
family: dm
name: coplanar_mesh
profile_name: dm_gripper_coplanar_mesh
path: assets/grippers/dm_gripper/parallel_gripper_coplanar_mesh_collision.xml
tactile:
  mode: contact_geom
  rows: 3
  cols: 3
  left_prefix: left_taxel_geom_
  right_prefix: right_taxel_geom_
sensor_taxel_normal_noise_std_n: [0.0066666667, 0.0133333333]
sensor_taxel_shear_noise_std_n: [0.0033333333, 0.01]
