schema_version: 1
name: robotiq_2f85_box_taxels

model:
  path: ../assets/grippers/robotiq_2f85/2f85_taxels_box.xml

control:
  mode: position
  actuator: fingers_actuator
  open: 0.0
  closed: 220.0

mount:
  pos: [0.0, 0.0, 0.08]
  quat: [0.70710678, 0.70710678, 0.0, 0.0]

tactile:
  mode: force_sensor
  rows: 3
  cols: 3
  left_prefix: left_taxel_force_
  right_prefix: right_taxel_force_
